const express = require('express');
const router = express.Router();

// POST - Add a new review
router.post('/add', async (req, res) => {
    const { listing_id, user_id, rating, comment } = req.body;

    // Log the incoming request to the terminal for debugging
    console.log("📥 New Review Request:", { listing_id, user_id, rating, comment });

    try {
        // 1. Validation: Ensure all required fields are present
        if (!listing_id || !user_id || !rating || !comment) {
            return res.status(400).json({ error: "All fields are required (listing_id, user_id, rating, comment)." });
        }

        // 2. Validate User Existence (Prevents Foreign Key crash)
        const [userCheck] = await req.pool.query('SELECT id FROM Users WHERE id = ?', [user_id]);
        if (userCheck.length === 0) {
            console.error(`❌ User with ID ${user_id} not found.`);
            return res.status(404).json({ error: "User not found. Please log out and log back in." });
        }

        // 3. Insert into Reviews table
        // We omit 'review_id' and 'created_at' as they are auto-generated by your DB
        const query = 'INSERT INTO Reviews (listing_id, user_id, rating, comment) VALUES (?, ?, ?, ?)';
        await req.pool.query(query, [listing_id, user_id, rating, comment]);

        console.log("✅ Review successfully saved to Aiven MySQL.");
        res.status(201).json({ message: "Review submitted successfully!" });

    } catch (err) {
        console.error("❌ Database Error:", err.message);
        
        // Handle specific Foreign Key errors (e.g., if listing_id doesn't exist)
        if (err.code === 'ER_NO_REFERENCED_ROW_2') {
            return res.status(400).json({ error: "This listing does not exist in the database." });
        }

        res.status(500).json({ error: "Internal Server Error: " + err.message });
    }
});

// GET - Fetch reviews for a specific listing
router.get('/:listing_id', async (req, res) => {
    const { listing_id } = req.params;
    
    try {
        // We JOIN with the Users table to get the name of the person who wrote the review
        const query = `
            SELECT r.review_id, r.rating, r.comment, r.created_at, u.name as reviewer_name 
            FROM Reviews r 
            JOIN Users u ON r.user_id = u.id 
            WHERE r.listing_id = ? 
            ORDER BY r.created_at DESC`;

        const [rows] = await req.pool.query(query, [listing_id]);
        res.json(rows);

    } catch (err) {
        console.error("❌ Fetch Error:", err.message);
        res.status(500).json({ error: err.message });
    }
});

module.exports = router;