version: '3.8'

services:
  backend:
    build:
      context: ./code/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./code/backend/.env

  frontend:
    build:
      context: ./code/front_end
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
